Repository insightsengineering/scda.test, pull requests merged in 2024-11, with the labels that each got.

#153 Use `pharmaverseadam` data in safety templates - part 1
  DESCRIPTION
  tests/testthat/_snaps/listing_cml01.md
  tests/testthat/_snaps/listing_cml02a_gl.md
  tests/testthat/_snaps/listing_cml02b_gl.md
  tests/testthat/_snaps/listing_egl01.md
  tests/testthat/_snaps/listing_exl01.md
  tests/testthat/_snaps/listing_lbl02a_rls.md
  tests/testthat/_snaps/table_cmt01.md
  tests/testthat/_snaps/table_cmt01a.md
  tests/testthat/_snaps/table_cmt01b.md
  tests/testthat/_snaps/table_cmt02_pt.md
  tests/testthat/_snaps/table_lbt03.md
  tests/testthat/setup.R
  tests/testthat/test-listing_cml01.R
  tests/testthat/test-listing_cml02a_gl.R
  tests/testthat/test-listing_cml02b_gl.R
  tests/testthat/test-listing_egl01.R
  tests/testthat/test-listing_exl01.R
  tests/testthat/test-table_cmt01.R
  tests/testthat/test-table_cmt01a.R
  tests/testthat/test-table_cmt01b.R
  tests/testthat/test-table_cmt02_pt.R
Labels: sme, priority, change needed

#160 close #158
  .github/workflows/check.yaml
  DESCRIPTION
  staged_dependencies.yaml
Labels: sme

#161 Revisit lbt03 creation
  DESCRIPTION
  tests/testthat/_snaps/table_lbt03.md
Labels: sme

#164 Empty-Commit
  .github/workflows/check.yaml
  DESCRIPTION
Labels: sme

#154 Use pharmaverseadam data in safety templates - part 2
  .github/workflows/docs.yaml
  DESCRIPTION
  tests/testthat/_snaps/table_egt01.md
  tests/testthat/_snaps/table_egt02.md
  tests/testthat/_snaps/table_egt03.md
  tests/testthat/_snaps/table_egt04.md
  tests/testthat/_snaps/table_egt05_qtcat.md
  tests/testthat/_snaps/table_ext01.md
  tests/testthat/_snaps/table_vst01.md
  tests/testthat/_snaps/table_vst02.md
  tests/testthat/setup.R
  tests/testthat/test-listing_egl01.R
  tests/testthat/test-table_egt01.R
  tests/testthat/test-table_egt02.R
  tests/testthat/test-table_egt03.R
  tests/testthat/test-table_egt04.R
  tests/testthat/test-table_egt05_qtcat.R
  tests/testthat/test-table_ext01.R
  tests/testthat/test-table_vst01.R
  tests/testthat/test-table_vst02.R
Labels: sme, priority, change needed

#171 Update DESCRIPTION
  DESCRIPTION
Labels: sme

#169 Update EG templates
  DESCRIPTION
  tests/testthat/_snaps/listing_egl01.md
  tests/testthat/_snaps/table_egt01.md
  tests/testthat/_snaps/table_egt02.md
  tests/testthat/_snaps/table_egt03.md
  tests/testthat/_snaps/table_egt05_qtcat.md
  tests/testthat/setup.R
  tests/testthat/test-listing_egl01.R
  tests/testthat/test-table_egt03.R
  tests/testthat/test-table_egt05_qtcat.R
Labels: sme, change needed
